# frozen_string_literal: true

require "json"
require "yaml"
require_relative "./data_generator"

COMMENT = <<~TXT
  #################################################
  ##                                             ##
  ##         THIS FILE IS AUTO-GENERATED         ##
  ##            DO NOT EDIT THIS FILE            ##
  ##    ADD NEW CORE REPOSITORIES TO REPOS.YML   ##
  ##                                             ##
  #################################################

TXT

data = YAML.load_file("../../_data/repos.yml")
new_data = []

data.each do |entry|
  username, repo = URI.parse(entry["url"]).path.split("/").drop(1)

  cores = DataGenerator.new(
    username,
    repo,
    entry["display_name"]
  ).call

  new_data << { username: username, cores: cores }
end

pp new_data
